size:
  width: 5
  height: 5
  scale: 0.5
zones:
  - name: ag1
    target_zone_name: ag2
    pose: [2.5,4.5]
    shape: [0,0.5]
    width: 1
  - name: ag2
    target_zone_name: ag1
    pose: [2.5,0]
    shape: [0,0.5]
    width: 1
  - name: ac1
    target_zone_name: ac2
    pose: [2.5,3]
    shape: [0,0.5]
    width: 0.5
  - name: ac2
    target_zone_name: ac1
    pose: [2.5,1.5]
    shape: [0,0.5]
    width: 0.5
viewer:
  show_nodes: false
  show_zones: true
  show_walls_mean: false
  show_walls_vertices: false
actor:
  config_rel_path: train/1.yml
  max_actor_num: 1
  convergence_radius: 1.0
agent:
  config_rel_path: for_old_method.yml
  max_agent_num: 1