size:
  width: 25
  height: 25
  scale: 0.7
walls:
  - name: wall1
    pose: [0,24.75]
    shape: [25,0]
    width: 0.5
  - name: wall2
    pose: [0.25,24.5]
    shape: [0,-10]
    width: 0.5
  - name: wall3
    pose: [1.25,15.5]
    shape:
      - [0,-14.25]
      - [14.25,0]
    width: 2.5
  - name: wall4
    pose: [19.75,0]
    shape:
      - [0,6.75]
      - [-5.75,0]
    width: 4.5
  - name: wall5
    pose: [23.5,0]
    shape: [0,11]
    width: 3
  - name: wall6
    pose: [25,19]
    shape:
      - [-8,0]
      - [0,-8]
    width: 6
  - name: wall7
    pose: [12,19.75]
    shape: [-9.5,0]
    width: 4.5
  - name: wall8
    pose: [12,13.25]
    shape: [-7.5,0]
    width: 4.5
  - name: wall9
    pose: [12,10]
    shape: [-1,0]
    width: 2
  - name: wall10
    pose: [12, 6.75]
    shape: [-7.5,0]
    width: 4.5
nodes:
  - name: node1
    pose: [3.5,16.5]
  - name: node2
    pose: [3.5,10]
  - name: node3
    pose: [3.5,3.5]
  - name: node4
    pose: [13,3.5]
  - name: node5
    pose: [16.5,3.5]
  - name: node6
    pose: [13,10]
  - name: node7
    pose: [21,10]
  - name: node8
    pose: [13,16.5]
  - name: node9
    pose: [13,23.25]
  - name: node10
    pose: [21, 12]
  - name: node11
    pose: [1.5, 16.5]
zones:
  - name: zone1
    pose: [0.5,23.25]
    shape: [2.5,0]
    width: 2.5
  - name: zone2
    pose: [16.5,0]
    shape: [0,1]
    width: 2
  - name: zone3
    pose: [25,13.5]
    shape: [-1,0]
    width: 5
  - name: zone4
    pose: [25,23.25]
    shape: [-1,0]
    width: 2.5
  - name: zone5
    pose: [11,10]
    shape: [-2,0]
    width: 2
viewer:
  show_nodes: false
  show_zones: false
  show_walls_mean: false
  show_walls_vertices: false
actor:
  config_rel_path: train/4.yml
  max_actor_num: 10
  convergence_radius: 1.0
agent:
  config_rel_path: default.yml
  max_agent_num: 1