size:
  width: 7
  height: 4
  scale: 0.5
walls:
  - name: wall1
    pose: [0,3]
    shape: [7,0]
    width: 0.1
  - name: wall2
    pose: [0,1]
    shape: [7,0]
    width: 0.1
zones:
  - name: ag1
    target_zone_name: ag2
    pose: [0,2]
    shape: [0.5,0]
    width: 0.5
  - name: ag2
    target_zone_name: ag1
    pose: [6.5,2]
    shape: [0.5,0]
    width: 0.5
  - name: ac1
    target_zone_name: ac2
    pose: [1,2]
    shape: [0.5,0]
    width: 1
  - name: ac2
    target_zone_name: ac1
    pose: [5.5,2]
    shape: [0.5,0]
    width: 1
viewer:
  show_nodes: false
  show_zones: false
  show_walls_mean: false
  show_walls_vertices: false
actor:
  config_rel_path: train/1.yml
  max_actor_num: 2
  convergence_radius: 1.0
agent:
  config_rel_path: default.yml
  max_agent_num: 1