size:
  width: 5
  height: 5
  scale: 0.5
walls:
  - name: wall1
    pose: [0.8,0]
    shape: [0,5]
    width: 0.3
  - name: wall2
    pose: [4.2,0]
    shape: [0,5]
    width: 0.3
  - name: wall3
    pose: [2.5,2]
    shape: [0,1]
    width: 1
zones:
  - name: ag1
    pose: [2.5,0.5]
    shape: [0,0.5]
    width: 2
  - name: ag2
    pose: [2.5,4]
    shape: [0,0.5]
    width: 2
viewer:
  show_nodes: false
  show_zones: false
  show_walls_mean: false
  show_walls_vertices: false
actor:
  config_rel_path: train/1.yml
  max_actor_num: 0
  convergence_radius: 1.0
agent:
  config_rel_path: default.yml
  max_agent_num: 1