size:
  width: 5
  height: 5
  scale: 0.5
zones:
  - name: ag1
    target_zone_name: ag2
    pose: [2.5,4.5]
    shape: [0,0.5]
    width: 1.2
  - name: ag2
    target_zone_name: ag1
    pose: [2.5,0]
    shape: [0,0.5]
    width: 1.2
  - name: ac1
    target_zone_name: ac2
    pose: [1,2.5]
    shape: [0.5,0]
    width: 1.2
  - name: ac2
    target_zone_name: ac1
    pose: [3.5,2.5]
    shape: [0.5,0]
    width: 1.2
walls:
  - name: wall1
    pose: [0,3.5]
    shape:
      - [1.5,0]
      - [0,1.5]
    width: 0.1
  - name: wall2
    pose: [3.5,5]
    shape:
      - [0,-1.5]
      - [1.5,0]
    width: 0.1
  - name: wall3
    pose: [5,1.5]
    shape:
      - [-1.5,0]
      - [0,-1.5]
    width: 0.1
  - name: wall4
    pose: [1.5,0]
    shape:
      - [0,1.5]
      - [-1.5,0]
    width: 0.1
viewer:
  show_nodes: false
  show_zones: false
  show_ng_zones: false
  show_walls_mean: false
  show_walls_vertices: false
actor:
  config_rel_path: train/1.yml
  max_actor_num: 2
  convergence_radius: 1.0
agent:
  config_rel_path: default.yml
  max_agent_num: 1