size:
  width: 4
  height: 6
  scale: 0.5
zones:
  - name: ag1
    target_zone_name: ag2
    pose: [2,5.5]
    shape: [0,0.5]
    width: 0.5
  - name: ag2
    target_zone_name: ag1
    pose: [2,0]
    shape: [0,0.5]
    width: 0.5
  - name: ac1
    target_zone_name: ac2
    pose: [1,1.5]
    shape: [-0.5,0]
    width: 0.5
  - name: ac2
    target_zone_name: ac1
    pose: [3,1.5]
    shape: [0.5,0]
    width: 0.5
  - name: ac3
    target_zone_name: ac4
    pose: [1,3]
    shape: [-0.5,0]
    width: 0.5
  - name: ac4
    target_zone_name: ac3
    pose: [3,3]
    shape: [0.5,0]
    width: 0.5
  - name: ac5
    target_zone_name: ac6
    pose: [1,4.5]
    shape: [-0.5,0]
    width: 0.5
  - name: ac6
    target_zone_name: ac5
    pose: [3,4.5]
    shape: [0.5,0]
    width: 0.5
viewer:
  show_nodes: false
  show_zones: true
  show_walls_mean: false
  show_walls_vertices: false
actor:
  config_rel_path: train/1.yml
  max_actor_num: 6
  convergence_radius: 1.0
agent:
  config_rel_path: for_old_method.yml
  max_agent_num: 1