size:
  width: 5
  height: 6
  scale: 0.5
walls:
  - name: wall1
    pose: [0,4]
    shape:
      - [1.5,0]
      - [0,2]
    width: 0.1
  - name: wall2
    pose: [3.5,6]
    shape:
      - [0,-2]
      - [1.5,0]
    width: 0.1
  - name: wall3
    pose: [5,2]
    shape:
      - [-1.5,0]
      - [0,-2]
    width: 0.1
  - name: wall4
    pose: [1.5,0]
    shape:
      - [0,2]
      - [-1.5,0]
    width: 0.1
zones:
  - name: ag1
    target_zone_name: ag2
    pose: [2.5,5.5]
    shape: [0,0.5]
    width: 1.2
  - name: ag2
    target_zone_name: ag1
    pose: [2.5,0]
    shape: [0,0.5]
    width: 1.2
  - name: ac1
    target_zone_name: ac2
    pose: [1,3]
    shape: [0.5,0]
    width: 1.2
  - name: ac2
    target_zone_name: ac1
    pose: [3.5,3]
    shape: [0.5,0]
    width: 1.2
  - name: ac3
    target_zone_name: ac4
    pose: [0,3]
    shape: [0.5,0]
    width: 1.2
  - name: ac4
    target_zone_name: ac3
    pose: [4.5,3]
    shape: [0.5,0]
    width: 1.2
  - name: ac5
    target_zone_name: ac6
    pose: [2.5,1.7]
    shape: [0,0.5]
    width: 1.2
  - name: ac6
    target_zone_name: ac5
    pose: [2.5,4.3]
    shape: [0,-0.5]
    width: 1.2
viewer:
  show_nodes: false
  show_zones: true
  show_ng_zones: false
  show_walls_mean: false
  show_walls_vertices: false
actor:
  config_rel_path: train/1.yml
  max_actor_num: 5
  convergence_radius: 1.0
agent:
  config_rel_path: default.yml
  max_agent_num: 1